name: transaction-processor-api
region: nyc
alerts:
  - rule: DEPLOYMENT_FAILED
    disabled: false
  - rule: DOMAIN_FAILED
    disabled: false

services:
  - name: api
    github:
      repo: ${{ secrets.GITHUB_REPO }}
      branch: main
      deploy_on_push: true
    dockerfile_path: docker/Dockerfile
    dockerfile_context: .
    source_dir: /
    build_command: npm ci && npm run build
    run_command: npm run migrate && node dist/main.js
    environment_slug: node-js
    instance_count: 2
    instance_size_slug: basic-xxs
    http_port: 3000
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      - key: PORT
        value: "3000"
        scope: RUN_TIME
      - key: DB_HOST
        value: ${db.HOSTNAME}
        scope: RUN_TIME
        type: SECRET
      - key: DB_PORT
        value: ${db.PORT}
        scope: RUN_TIME
        type: SECRET
      - key: DB_USER
        value: ${db.USERNAME}
        scope: RUN_TIME
        type: SECRET
      - key: DB_PASSWORD
        value: ${db.PASSWORD}
        scope: RUN_TIME
        type: SECRET
      - key: DB_NAME
        value: ${db.DATABASE}
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_HOST
        value: "redis"
        scope: RUN_TIME
      - key: REDIS_PORT
        value: "6379"
        scope: RUN_TIME
      - key: REDIS_PASSWORD
        value: ""
        scope: RUN_TIME
      - key: LOG_LEVEL
        value: info
        scope: RUN_TIME
      - key: BULLMQ_QUEUE_NAME
        value: transactions
        scope: RUN_TIME
      - key: BULLMQ_DEFAULT_ATTEMPTS
        value: "3"
        scope: RUN_TIME
      - key: BULLMQ_BACKOFF_DELAY
        value: "2000"
        scope: RUN_TIME
    cors:
      allow_origins:
        - exact: "*"
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allow_headers:
        - Content-Type
        - Authorization
      max_age: 3600

databases:
  - name: db
    engine: PG
    version: "15"
    production: true
    cluster_name: transaction-db-cluster
    db_name: transactions_db
    db_user: transaction_user

