import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export enum TransactionType {
  CREDIT = 'credit',
  DEBIT = 'debit',
}

export enum TransactionStatus {
  PENDING = 'pending',
  COMPLETED = 'completed',
  FAILED = 'failed',
}

export class Transaction {
  @ApiProperty({
    description:
      'Unique identifier (UUID) generated by the system for this transaction',
    example: '123e4567-e89b-12d3-a456-426614174000',
    format: 'uuid',
    examples: {
      'UUID Example 1': {
        value: '123e4567-e89b-12d3-a456-426614174000',
        summary: 'Standard UUID format',
      },
      'UUID Example 2': {
        value: '987fcdeb-51a2-43f7-8b9c-123456789abc',
        summary: 'Another UUID example',
      },
    },
  })
  id: string;

  @ApiProperty({
    description:
      'External transaction ID provided by the client. This is used for idempotency - if a transaction with this ID already exists, the existing transaction is returned instead of creating a duplicate.',
    example: 'txn-2024-01-15-abc123def456',
    maxLength: 255,
    examples: {
      'Payment Gateway ID': {
        value: 'pg-payment-12345-20240115',
        summary: 'Payment gateway transaction ID',
      },
      'Order ID': {
        value: 'order-789456-2024-01-15',
        summary: 'E-commerce order ID',
      },
    },
  })
  transactionId: string;

  @ApiProperty({
    description:
      'Transaction amount in the specified currency. Always has maximum 2 decimal places.',
    example: 100.5,
    minimum: 0,
    examples: {
      'Small Amount': {
        value: 10.99,
        summary: 'Small transaction',
      },
      'Medium Amount': {
        value: 1000.5,
        summary: 'Medium transaction',
      },
      'Large Amount': {
        value: 50000.0,
        summary: 'Large transaction',
      },
    },
  })
  amount: number;

  @ApiProperty({
    description: 'Currency code following ISO 4217 standard',
    example: 'BRL',
    enum: [
      'USD',
      'EUR',
      'GBP',
      'BRL',
      'JPY',
      'AUD',
      'CAD',
      'CHF',
      'CNY',
      'SEK',
      'NZD',
      'MXN',
      'SGD',
      'HKD',
      'NOK',
      'TRY',
      'RUB',
      'INR',
      'ZAR',
      'DKK',
      'PLN',
      'TWD',
      'THB',
      'MYR',
      'CZK',
      'HUF',
      'ILS',
      'CLP',
      'PHP',
      'AED',
      'COP',
      'SAR',
      'IDR',
      'KRW',
      'EGP',
      'IQD',
      'ARS',
      'VND',
      'PKR',
      'BGN',
    ],
    examples: {
      'Brazilian Real': {
        value: 'BRL',
        summary: 'Brazilian Real',
      },
      'US Dollar': {
        value: 'USD',
        summary: 'US Dollar',
      },
      Euro: {
        value: 'EUR',
        summary: 'Euro',
      },
    },
  })
  currency: string;

  @ApiProperty({
    description:
      'Type of transaction. CREDIT means money received, DEBIT means money sent.',
    enum: TransactionType,
    example: TransactionType.CREDIT,
    examples: {
      Credit: {
        value: TransactionType.CREDIT,
        summary: 'Credit transaction (money received)',
      },
      Debit: {
        value: TransactionType.DEBIT,
        summary: 'Debit transaction (money sent)',
      },
    },
  })
  type: TransactionType;

  @ApiProperty({
    description: 'Current status of the transaction',
    enum: TransactionStatus,
    example: TransactionStatus.PENDING,
    examples: {
      Pending: {
        value: TransactionStatus.PENDING,
        summary: 'Transaction is pending processing',
      },
      Completed: {
        value: TransactionStatus.COMPLETED,
        summary: 'Transaction has been completed successfully',
      },
      Failed: {
        value: TransactionStatus.FAILED,
        summary: 'Transaction has failed',
      },
    },
  })
  status: TransactionStatus;

  @ApiPropertyOptional({
    description:
      'Additional metadata associated with the transaction. Can contain any custom fields.',
    example: {
      source: 'payment-gateway',
      reference: 'order-123',
      customerId: 'cust-456',
      paymentMethod: 'credit-card',
      merchantId: 'merchant-789',
    },
    examples: {
      'Payment Gateway': {
        value: {
          source: 'stripe',
          paymentIntentId: 'pi_1234567890',
          customerEmail: 'customer@example.com',
        },
        summary: 'Payment gateway metadata',
      },
      'E-commerce': {
        value: {
          source: 'ecommerce-platform',
          orderId: 'ORD-12345',
          customerId: 'CUST-67890',
        },
        summary: 'E-commerce metadata',
      },
      'Empty Metadata': {
        value: null,
        summary: 'No metadata provided',
      },
    },
  })
  metadata?: Record<string, any>;

  @ApiProperty({
    description: 'ISO 8601 timestamp when the transaction was created',
    example: '2024-01-15T10:30:00.000Z',
    format: 'date-time',
    examples: {
      Recent: {
        value: '2024-01-15T10:30:00.000Z',
        summary: 'Recent transaction',
      },
      Older: {
        value: '2024-01-01T00:00:00.000Z',
        summary: 'Older transaction',
      },
    },
  })
  createdAt: Date;

  @ApiProperty({
    description: 'ISO 8601 timestamp when the transaction was last updated',
    example: '2024-01-15T10:30:00.000Z',
    format: 'date-time',
    examples: {
      Updated: {
        value: '2024-01-15T10:35:00.000Z',
        summary: 'Transaction that was updated',
      },
      'Not Updated': {
        value: '2024-01-15T10:30:00.000Z',
        summary: 'Transaction that was never updated (same as createdAt)',
      },
    },
  })
  updatedAt: Date;
}

export interface TransactionRow {
  id: string;
  transaction_id: string;
  amount: number;
  currency: string;
  type: string;
  status: string;
  metadata?: Record<string, any>;
  created_at: Date;
  updated_at: Date;
}
